import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Qr - Code</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          AMOGUS
        </h1>


        <div className={styles.grid}>
          <a href="/scan" className={styles.card}>
            <h2>Start&rarr;</h2>
            <p>Scanne QR-Code deiner Rollenkarte</p>
          </a>

          <a href="/generate" className={styles.card}>
            <h2>Überwachung&rarr;</h2>
            <p>Das Panel für den Admin</p>
          </a>
        </div>
      </main>
    </div>
  )
}